var allMedia = [
    {string: '🌂', type: 'image', doc: require('../assets/img/png/1f302.png'), correctWord: 'Parapluie'},
    {string: '🌋', type: 'image', doc: require('../assets/img/png/1f30b.png'), correctWord: 'Volcan'},
    {string: '🌍', type: 'image', doc: require('../assets/img/png/1f30d.png'), correctWord: 'Terre'},
    {string: '🌜', type: 'image', doc: require('../assets/img/png/1f31c.png'), correctWord: 'Lune'},
    {string: '🌞', type: 'image', doc: require('../assets/img/png/1f31e.png'), correctWord: 'Soleil'},
    {string: '🌪', type: 'image', doc: require('../assets/img/png/1f32a.png'), correctWord: 'Tornade'},
    {string: '🌵', type: 'image', doc: require('../assets/img/png/1f335.png'), correctWord: 'Cactus'},
    {string: '🌶', type: 'image', doc: require('../assets/img/png/1f336.png'), correctWord: 'Piment'},
    {string: '🌹', type: 'image', doc: require('../assets/img/png/1f339.png'), correctWord: 'Fleur'},
    {string: '🌻', type: 'image', doc: require('../assets/img/png/1f33b.png'), correctWord: 'Fleur', words:{level_3: ['Fruit', 'Fanée', 'Faisan', 'Feuillu', 'Feuille', 'Flair']}},
    {string: '🌽', type: 'image', doc: require('../assets/img/png/1f33d.png'), correctWord: 'Maïs'},
    {string: '🍁', type: 'image', doc: require('../assets/img/png/1f341.png'), correctWord: 'Feuille', words:{level_3: ['Fleur', 'Fruit', 'Fanée', 'Faisan', 'Feuillu']}},
    {string: '🍄', type: 'image', doc: require('../assets/img/png/1f344.png'), correctWord: 'Champignon'},
    {string: '🍅', type: 'image', doc: require('../assets/img/png/1f345.png'), correctWord: 'Tomate', words:{level_3: ['Tombé', 'Tornade', 'Tonelle', 'Tourner', 'Toundra']}},
    {string: '🍆', type: 'image', doc: require('../assets/img/png/1f346.png'), correctWord: 'Aubergine'},
    {string: '🍇', type: 'image', doc: require('../assets/img/png/1f347.png'), correctWord: 'Raisin'},
    {string: '🍊', type: 'image', doc: require('../assets/img/png/1f34a.png'), correctWord: 'Pêche'},
    {string: '🍋', type: 'image', doc: require('../assets/img/png/1f34b.png'), correctWord: 'Citron'},
    {string: '🍌', type: 'image', doc: require('../assets/img/png/1f34c.png'), correctWord: 'Banane'},
    {string: '🍍', type: 'image', doc: require('../assets/img/png/1f34d.png'), correctWord: 'Ananas'},
    {string: '🍎', type: 'image', doc: require('../assets/img/png/1f34e.png'), correctWord: 'Pomme'},
    {string: '🍐', type: 'image', doc: require('../assets/img/png/1f350.png'), correctWord: 'Poire'},
    {string: '🍒', type: 'image', doc: require('../assets/img/png/1f352.png'), correctWord: 'Cerise'},
    {string: '🍓', type: 'image', doc: require('../assets/img/png/1f353.png'), correctWord: 'Fraise', words:{level_3: ['Fleur', 'Frêne', 'Feuille', 'Flamant', 'Fauteuil']}},
    {string: '🍞', type: 'image', doc: require('../assets/img/png/1f35e.png'), correctWord: 'Pain'},
    {string: '🍫', type: 'image', doc: require('../assets/img/png/1f36b.png'), correctWord: 'Chocolat'},
    {string: '🍬', type: 'image', doc: require('../assets/img/png/1f36c.png'), correctWord: 'Bonbon', words:{level_3: ['Bonnet', 'Bouteille', 'Biberon', 'Bateau', 'Bâton']}},
    {string: '🍼', type: 'image', doc: require('../assets/img/png/1f37c.png'), correctWord: 'Biberon', words:{level_3: ['Bonnet', 'Bouteille', 'Bonbon', 'Bateau', 'Bâton']}},
    {string: '🎣', type: 'image', doc: require('../assets/img/png/1f3a3.png'), correctWord: 'Pêcher'},
    {string: '🎤', type: 'image', doc: require('../assets/img/png/1f3a4.png'), correctWord: 'Micro'},
    {string: '🎥', type: 'image', doc: require('../assets/img/png/1f3a5.png'), correctWord: 'Caméra'},
    {string: '🎨', type: 'image', doc: require('../assets/img/png/1f3a8.png'), correctWord: 'Palette'},
    {string: '🎩', type: 'image', doc: require('../assets/img/png/1f3a9.png'), correctWord: 'Chapeau'},
    {string: '🎪', type: 'image', doc: require('../assets/img/png/1f3aa.png'), correctWord: 'Cirque'},
    {string: '🎲', type: 'image', doc: require('../assets/img/png/1f3b2.png'), correctWord: 'Dé'},
    {string: '🎷', type: 'image', doc: require('../assets/img/png/1f3b7.png'), correctWord: 'Saxophone'},
    {string: '🎸', type: 'image', doc: require('../assets/img/png/1f3b8.png'), correctWord: 'Guitare'},
    {string: '🎻', type: 'image', doc: require('../assets/img/png/1f3bb.png'), correctWord: 'Violon'},
    {string: '🎾', type: 'image', doc: require('../assets/img/png/1f3be.png'), correctWord: 'Balle'},
    {string: '🎿', type: 'image', doc: require('../assets/img/png/1f3bf.png'), correctWord: 'Skis'},
    {string: '🏀', type: 'image', doc: require('../assets/img/png/1f3c0.png'), correctWord: 'Ballon', words:{level_3: ['Bonnet', 'Bouteille', 'Bonbon', 'Bateau', 'Bâton']}},
    {string: '🏃', type: 'image', doc: require('../assets/img/png/1f3c3.png'), correctWord: 'Courir'},
    {string: '🏄', type: 'image', doc: require('../assets/img/png/1f3c4.png'), correctWord: 'Surfer'},
    {string: '🏇', type: 'image', doc: require('../assets/img/png/1f3c7.png'), correctWord: 'Equitation'},
    {string: '🏊', type: 'image', doc: require('../assets/img/png/1f3ca.png'), correctWord: 'Nager'},
    {string: '🏋', type: 'image', doc: require('../assets/img/png/1f3cb.png'), correctWord: 'Haltère'},
    {string: '🏍', type: 'image', doc: require('../assets/img/png/1f3cd.png'), correctWord: 'Moto'},
    {string: '🏗', type: 'image', doc: require('../assets/img/png/1f3d7.png'), correctWord: 'Grue'},
    {string: '🏘', type: 'image', doc: require('../assets/img/png/1f3d8.png'), correctWord: 'Village'},
    {string: '🏜', type: 'image', doc: require('../assets/img/png/1f3dc.png'), correctWord: 'Désert'},
    {string: '🏝', type: 'image', doc: require('../assets/img/png/1f3dd.png'), correctWord: 'Île'},
    {string: '🏠', type: 'image', doc: require('../assets/img/png/1f3e0.png'), correctWord: 'Maison'},
    {string: '🏭', type: 'image', doc: require('../assets/img/png/1f3ed.png'), correctWord: 'Usine'},
    {string: '🐀', type: 'image', doc: require('../assets/img/png/1f400.png'), correctWord: 'Souris'},
    {string: '🐄', type: 'image', doc: require('../assets/img/png/1f404.png'), correctWord: 'Vache'},
    {string: '🐅', type: 'image', doc: require('../assets/img/png/1f405.png'), correctWord: 'Tigre'},
    {string: '🐆', type: 'image', doc: require('../assets/img/png/1f406.png'), correctWord: 'Léopard'},
    {string: '🐇', type: 'image', doc: require('../assets/img/png/1f407.png'), correctWord: 'Lapin'},
    {string: '🐈', type: 'image', doc: require('../assets/img/png/1f408.png'), correctWord: 'Chat'},
    {string: '🐉', type: 'image', doc: require('../assets/img/png/1f409.png'), correctWord: 'Dragon'},
    {string: '🐊', type: 'image', doc: require('../assets/img/png/1f40a.png'), correctWord: 'Crocodile'},
    {string: '🐋', type: 'image', doc: require('../assets/img/png/1f40b.png'), correctWord: 'Baleine'},
    {string: '🐌', type: 'image', doc: require('../assets/img/png/1f40c.png'), correctWord: 'Escargot'},
    {string: '🐍', type: 'image', doc: require('../assets/img/png/1f40d.png'), correctWord: 'Serpent'},
    {string: '🐎', type: 'image', doc: require('../assets/img/png/1f40e.png'), correctWord: 'Cheval'},
    {string: '🐏', type: 'image', doc: require('../assets/img/png/1f40f.png'), correctWord: 'Mouton', words:{level_3: ['Montagne', 'Mousse', 'Moulin', 'Marteau', 'Maison']}},
    {string: '🐐', type: 'image', doc: require('../assets/img/png/1f410.png'), correctWord: 'Chèvre'},
    {string: '🐒', type: 'image', doc: require('../assets/img/png/1f412.png'), correctWord: 'Singe', words:{level_3: ['Serpent', 'Soleil', 'Cerise', 'Chien', 'Chat']}},
    {string: '🐓', type: 'image', doc: require('../assets/img/png/1f413.png'), correctWord: 'Poule'},
    {string: '🐕', type: 'image', doc: require('../assets/img/png/1f415.png'), correctWord: 'Chien'},
    {string: '🐖', type: 'image', doc: require('../assets/img/png/1f416.png'), correctWord: 'Cochon'},
    {string: '🐘', type: 'image', doc: require('../assets/img/png/1f418.png'), correctWord: 'Éléphant'},
    {string: '🐙', type: 'image', doc: require('../assets/img/png/1f419.png'), correctWord: 'Poulpe'},
    {string: '🐚', type: 'image', doc: require('../assets/img/png/1f41a.png'), correctWord: 'Coquillage'},
    {string: '🐛', type: 'image', doc: require('../assets/img/png/1f41b.png'), correctWord: 'Chenille'},
    {string: '🐜', type: 'image', doc: require('../assets/img/png/1f41c.png'), correctWord: 'Fourmi'},
    {string: '🐝', type: 'image', doc: require('../assets/img/png/1f41d.png'), correctWord: 'Abeille', words:{level_3: ['Appareil photo', 'Ampoule', 'Avocat', 'Ancre', 'Avion']}},
    {string: '🐞', type: 'image', doc: require('../assets/img/png/1f41e.png'), correctWord: 'Coccinelle'},
    {string: '🐟', type: 'image', doc: require('../assets/img/png/1f41f.png'), correctWord: 'Poisson'},
    {string: '🐠', type: 'image', doc: require('../assets/img/png/1f420.png'), correctWord: 'Poisson'},
    {string: '🐢', type: 'image', doc: require('../assets/img/png/1f422.png'), correctWord: 'Tortue'},
    {string: '🐣', type: 'image', doc: require('../assets/img/png/1f423.png'), correctWord: 'Poussin'},
    {string: '🐩', type: 'image', doc: require('../assets/img/png/1f429.png'), correctWord: 'Chien'},
    {string: '🐫', type: 'image', doc: require('../assets/img/png/1f42b.png'), correctWord: 'Chameau'},
    {string: '🐬', type: 'image', doc: require('../assets/img/png/1f42c.png'), correctWord: 'Dauphin', words:{level_3: ['Dromadaire', 'Dragon', 'Dé', 'Danser', 'Grue']}},
    {string: '🐿', type: 'image', doc: require('../assets/img/png/1f43f.png'), correctWord: 'Écureuil', words:{level_3: ['Éléphant', 'Étoile', 'Café', 'Poussin', 'Maïs']}},
    {string: '👃', type: 'image', doc: require('../assets/img/png/1f443.png'), correctWord: 'Nez'},
    {string: '👄', type: 'image', doc: require('../assets/img/png/1f444.png'), correctWord: 'Bouche'},
    {string: '👓', type: 'image', doc: require('../assets/img/png/1f453.png'), correctWord: 'Lunettes'},
    {string: '👕', type: 'image', doc: require('../assets/img/png/1f455.png'), correctWord: 'Chemise'},
    {string: '👖', type: 'image', doc: require('../assets/img/png/1f456.png'), correctWord: 'Pantalon'},
    {string: '👗', type: 'image', doc: require('../assets/img/png/1f457.png'), correctWord: 'Robe'},
    {string: '👞', type: 'image', doc: require('../assets/img/png/1f45e.png'), correctWord: 'Chaussure'},
    {string: '👟', type: 'image', doc: require('../assets/img/png/1f45f.png'), correctWord: 'Chaussure'},
    {string: '👠', type: 'image', doc: require('../assets/img/png/1f460.png'), correctWord: 'Chaussure'},
    {string: '👡', type: 'image', doc: require('../assets/img/png/1f461.png'), correctWord: 'Chaussure'},
    {string: '💡', type: 'image', doc: require('../assets/img/png/1f4a1.png'), correctWord: 'Ampoule'},
    {string: '💼', type: 'image', doc: require('../assets/img/png/1f4bc.png'), correctWord: 'Valise'},
    {string: '📸', type: 'image', doc: require('../assets/img/png/1f4f8.png'), correctWord: 'Appareil Photo'},
    {string: '🔔', type: 'image', doc: require('../assets/img/png/1f514.png'), correctWord: 'Cloche'},
    {string: '🔥', type: 'image', doc: require('../assets/img/png/1f525.png'), correctWord: 'Feu'},
    {string: '🔦', type: 'image', doc: require('../assets/img/png/1f526.png'), correctWord: 'Lampe'},
    {string: '🔨', type: 'image', doc: require('../assets/img/png/1f528.png'), correctWord: 'Marteau'},
    {string: '🕺', type: 'image', doc: require('../assets/img/png/1f57a.png'), correctWord: 'Danser'},
    {string: '🖨', type: 'image', doc: require('../assets/img/png/1f5a8.png'), correctWord: 'Imprimante'},
    {string: '😀', type: 'image', doc: require('../assets/img/png/1f600.png'), correctWord: ''},
    {string: '😁', type: 'image', doc: require('../assets/img/png/1f601.png'), correctWord: ''},
    {string: '😆', type: 'image', doc: require('../assets/img/png/1f606.png'), correctWord: ''},
    {string: '😓', type: 'image', doc: require('../assets/img/png/1f613.png'), correctWord: ''},
    {string: '😖', type: 'image', doc: require('../assets/img/png/1f616.png'), correctWord: ''},
    {string: '😩', type: 'image', doc: require('../assets/img/png/1f629.png'), correctWord: ''},
    {string: '😱', type: 'image', doc: require('../assets/img/png/1f631.png'), correctWord: ''},
    {string: '😿', type: 'image', doc: require('../assets/img/png/1f63f.png'), correctWord: ''},
    {string: '🙁', type: 'image', doc: require('../assets/img/png/1f641.png'), correctWord: 'Triste'},
    {string: '🙇', type: 'image', doc: require('../assets/img/png/1f647.png'), correctWord: 'dommage'},
    {string: '🚛', type: 'image', doc: require('../assets/img/png/1f69b.png'), correctWord: 'Camion'},
    {string: '🚜', type: 'image', doc: require('../assets/img/png/1f69c.png'), correctWord: 'Tracteur'},
    {string: '🚣', type: 'image', doc: require('../assets/img/png/1f6a3.png'), correctWord: 'Ramer'},
    {string: '🚲', type: 'image', doc: require('../assets/img/png/1f6b2.png'), correctWord: 'Vélo'},
    {string: '🚴', type: 'image', doc: require('../assets/img/png/1f6b4.png'), correctWord: 'Vélo'},
    {string: '🚵', type: 'image', doc: require('../assets/img/png/1f6b5.png'), correctWord: 'Vélo'},
    {string: '🚶', type: 'image', doc: require('../assets/img/png/1f6b6.png'), correctWord: 'Marcher'},
    {string: '🚽', type: 'image', doc: require('../assets/img/png/1f6bd.png'), correctWord: 'Toilette'},
    {string: '🛀', type: 'image', doc: require('../assets/img/png/1f6c0.png'), correctWord: 'Baignoire'},
    {string: '🛁', type: 'image', doc: require('../assets/img/png/1f6c1.png'), correctWord: 'Baignoire'},
    {string: '🛣', type: 'image', doc: require('../assets/img/png/1f6e3.png'), correctWord: 'Route'},
    {string: '🛰', type: 'image', doc: require('../assets/img/png/1f6f0.png'), correctWord: 'Satellite'},
    {string: '🤦', type: 'image', doc: require('../assets/img/png/1f926.png'), correctWord: 'Oups'},
    {string: '🤷', type: 'image', doc: require('../assets/img/png/1f937.png'), correctWord: 'Dommage'},
    {string: '🤹', type: 'image', doc: require('../assets/img/png/1f939.png'), correctWord: 'Jongler'},
    {string: '🤻', type: 'image', doc: require('../assets/img/png/1f93b.png'), correctWord: ''},
    {string: '🥁', type: 'image', doc: require('../assets/img/png/1f941.png'), correctWord: 'Tambour'},
    {string: '🥐', type: 'image', doc: require('../assets/img/png/1f950.png'), correctWord: 'Croissant'},
    {string: '🥑', type: 'image', doc: require('../assets/img/png/1f951.png'), correctWord: 'Avocat'},
    {string: '🥒', type: 'image', doc: require('../assets/img/png/1f952.png'), correctWord: 'Concombre'},
    {string: '🥕', type: 'image', doc: require('../assets/img/png/1f955.png'), correctWord: 'Carotte'},
    {string: '🥖', type: 'image', doc: require('../assets/img/png/1f956.png'), correctWord: 'Pain'},
    {string: '🥝', type: 'image', doc: require('../assets/img/png/1f95d.png'), correctWord: 'Kiwi'},
    {string: '🦄', type: 'image', doc: require('../assets/img/png/1f984.png'), correctWord: 'Licorne'},
    {string: '🦅', type: 'image', doc: require('../assets/img/png/1f985.png'), correctWord: 'Aigle'},
    {string: '🦆', type: 'image', doc: require('../assets/img/png/1f986.png'), correctWord: 'Canard'},
    {string: '🦇', type: 'image', doc: require('../assets/img/png/1f987.png'), correctWord: 'Chauve-souris'},
    {string: '🦈', type: 'image', doc: require('../assets/img/png/1f988.png'), correctWord: 'Requin'},
    {string: '🦉', type: 'image', doc: require('../assets/img/png/1f989.png'), correctWord: 'Hibou'},
    {string: '🦎', type: 'image', doc: require('../assets/img/png/1f98e.png'), correctWord: 'Gecko'},
    {string: '☕', type: 'image', doc: require('../assets/img/png/2615.png'), correctWord: 'Café'},
    {string: '⚓', type: 'image', doc: require('../assets/img/png/2693.png'), correctWord: 'Ancre', words:{level_3: ['Avion', 'Ampoule', 'Ananas', 'Aubergine', 'Aigle']}},
    {string: '✂', type: 'image', doc: require('../assets/img/png/2702.png'), correctWord: 'Ciseaux'},
    {string: '✈', type: 'image', doc: require('../assets/img/png/2708.png'), correctWord: 'Avion', words:{level_3: ['Ancre', 'Ampoule', 'Ananas', 'Aubergine', 'Aigle']}},
]

export default allMedia