var allMedia = [
    {string: '🌂', type: 'image', doc: require('../assets/img/png/1f302.png'), correctWord: 'Parapluie', difficulty: 2},
    {string: '🌋', type: 'image', doc: require('../assets/img/png/1f30b.png'), correctWord: 'Volcan', difficulty: 2},
    {string: '🌍', type: 'image', doc: require('../assets/img/png/1f30d.png'), correctWord: 'Terre', difficulty: 2},
    {string: '🌜', type: 'image', doc: require('../assets/img/png/1f31c.png'), correctWord: 'Lune', difficulty: 1},
    {string: '🌞', type: 'image', doc: require('../assets/img/png/1f31e.png'), correctWord: 'Soleil', difficulty: 2},
    {string: '🌪', type: 'image', doc: require('../assets/img/png/1f32a.png'), correctWord: 'Tornade', difficulty: 2},
    {string: '🌵', type: 'image', doc: require('../assets/img/png/1f335.png'), correctWord: 'Cactus', difficulty: 2},
    {string: '🌶', type: 'image', doc: require('../assets/img/png/1f336.png'), correctWord: 'Piment', difficulty: 3},
    {string: '🌹', type: 'image', doc: require('../assets/img/png/1f339.png'), correctWord: 'Fleur', difficulty: 3},
    {string: '🌻', type: 'image', doc: require('../assets/img/png/1f33b.png'), correctWord: 'Fleur', words:{level_3: ['Fruit', 'Fanée', 'Faisan', 'Feuillu', 'Feuille', 'Flair']}, difficulty: 3},
    {string: '🌽', type: 'image', doc: require('../assets/img/png/1f33d.png'), correctWord: 'Maïs', difficulty: 3},
    {string: '🍁', type: 'image', doc: require('../assets/img/png/1f341.png'), correctWord: 'Feuille', words:{level_3: ['Fleur', 'Fruit', 'Fanée', 'Faisan', 'Feuillu']}, difficulty: 3},
    {string: '🍄', type: 'image', doc: require('../assets/img/png/1f344.png'), correctWord: 'Champignon', difficulty: 4},
    {string: '🍅', type: 'image', doc: require('../assets/img/png/1f345.png'), correctWord: 'Tomate', words:{level_3: ['Tombé', 'Tornade', 'Tonelle', 'Tourner', 'Toundra']}, difficulty: 1},
    {string: '🍆', type: 'image', doc: require('../assets/img/png/1f346.png'), correctWord: 'Aubergine', difficulty: 3},
    {string: '🍇', type: 'image', doc: require('../assets/img/png/1f347.png'), correctWord: 'Raisin', difficulty: 2},
    {string: '🍊', type: 'image', doc: require('../assets/img/png/1f34a.png'), correctWord: 'Orange', difficulty: 2},
    {string: '🍋', type: 'image', doc: require('../assets/img/png/1f34b.png'), correctWord: 'Citron', difficulty: 2},
    {string: '🍌', type: 'image', doc: require('../assets/img/png/1f34c.png'), correctWord: 'Banane', difficulty: 1},
    {string: '🍍', type: 'image', doc: require('../assets/img/png/1f34d.png'), correctWord: 'Ananas', difficulty: 1},
    {string: '🍎', type: 'image', doc: require('../assets/img/png/1f34e.png'), correctWord: 'Pomme', difficulty: 2},
    {string: '🍐', type: 'image', doc: require('../assets/img/png/1f350.png'), correctWord: 'Poire', difficulty: 2},
    {string: '🍒', type: 'image', doc: require('../assets/img/png/1f352.png'), correctWord: 'Cerise', difficulty: 1},
    {string: '🍓', type: 'image', doc: require('../assets/img/png/1f353.png'), correctWord: 'Fraise', words:{level_3: ['Fleur', 'Frêne', 'Feuille', 'Flamant', 'Fauteuil']}, difficulty: 2},
    {string: '🍞', type: 'image', doc: require('../assets/img/png/1f35e.png'), correctWord: 'Pain', difficulty: 3},
    {string: '🍫', type: 'image', doc: require('../assets/img/png/1f36b.png'), correctWord: 'Chocolat', difficulty: 2},
    {string: '🍬', type: 'image', doc: require('../assets/img/png/1f36c.png'), correctWord: 'Bonbon', words:{level_3: ['Bonnet', 'Bouteille', 'Biberon', 'Bateau', 'Bâton']}, difficulty: 2},
    {string: '🍼', type: 'image', doc: require('../assets/img/png/1f37c.png'), correctWord: 'Biberon', words:{level_3: ['Bonnet', 'Bouteille', 'Bonbon', 'Bateau', 'Bâton']}, difficulty: 2},
    {string: '🎣', type: 'image', doc: require('../assets/img/png/1f3a3.png'), correctWord: 'Pêcher'},
    {string: '🎤', type: 'image', doc: require('../assets/img/png/1f3a4.png'), correctWord: 'Micro', difficulty: 2},
    {string: '🎥', type: 'image', doc: require('../assets/img/png/1f3a5.png'), correctWord: 'Caméra', difficulty: 2},
    {string: '🎨', type: 'image', doc: require('../assets/img/png/1f3a8.png'), correctWord: 'Peinture', difficulty: 3},
    {string: '🎩', type: 'image', doc: require('../assets/img/png/1f3a9.png'), correctWord: 'Chapeau', difficulty: 2},
    {string: '🎪', type: 'image', doc: require('../assets/img/png/1f3aa.png'), correctWord: 'Cirque', difficulty: 3},
    {string: '🎲', type: 'image', doc: require('../assets/img/png/1f3b2.png'), correctWord: 'Dé'},
    {string: '🎷', type: 'image', doc: require('../assets/img/png/1f3b7.png'), correctWord: 'Saxophone', difficulty: 4},
    {string: '🎸', type: 'image', doc: require('../assets/img/png/1f3b8.png'), correctWord: 'Guitare', difficulty: 3},
    {string: '🎻', type: 'image', doc: require('../assets/img/png/1f3bb.png'), correctWord: 'Violon', difficulty: 3},
    {string: '🎾', type: 'image', doc: require('../assets/img/png/1f3be.png'), correctWord: 'Tennis', difficulty: 2},
    {string: '🎿', type: 'image', doc: require('../assets/img/png/1f3bf.png'), correctWord: 'Skis', difficulty: 2},
    {string: '🏀', type: 'image', doc: require('../assets/img/png/1f3c0.png'), correctWord: 'Ballon', words:{level_3: ['Bonnet', 'Bouteille', 'Bonbon', 'Bateau', 'Bâton']}, difficulty: 2},
    {string: '🏃', type: 'image', doc: require('../assets/img/png/1f3c3.png'), correctWord: 'Courir', difficulty: 2},
    {string: '🏄', type: 'image', doc: require('../assets/img/png/1f3c4.png'), correctWord: 'Surfer', difficulty: 3},
    {string: '🏇', type: 'image', doc: require('../assets/img/png/1f3c7.png'), correctWord: 'Equitation', difficulty: 4},
    {string: '🏊', type: 'image', doc: require('../assets/img/png/1f3ca.png'), correctWord: 'Nager', difficulty: 3},
    {string: '🏋', type: 'image', doc: require('../assets/img/png/1f3cb.png'), correctWord: 'Haltère', difficulty: 4},
    {string: '🏍', type: 'image', doc: require('../assets/img/png/1f3cd.png'), correctWord: 'Moto', difficulty: 1},
    {string: '🏗', type: 'image', doc: require('../assets/img/png/1f3d7.png'), correctWord: 'Grue', difficulty: 1},
    {string: '🏘', type: 'image', doc: require('../assets/img/png/1f3d8.png'), correctWord: 'Village', difficulty: 2},
    {string: '🏜', type: 'image', doc: require('../assets/img/png/1f3dc.png'), correctWord: 'Désert', difficulty: 2},
    {string: '🏝', type: 'image', doc: require('../assets/img/png/1f3dd.png'), correctWord: 'Île', difficulty: 1},
    {string: '🏠', type: 'image', doc: require('../assets/img/png/1f3e0.png'), correctWord: 'Maison', difficulty: 2},
    {string: '🏭', type: 'image', doc: require('../assets/img/png/1f3ed.png'), correctWord: 'Usine', difficulty: 1},
    {string: '🐀', type: 'image', doc: require('../assets/img/png/1f400.png'), correctWord: 'Souris', difficulty: 2},
    {string: '🐄', type: 'image', doc: require('../assets/img/png/1f404.png'), correctWord: 'Vache', difficulty: 1},
    {string: '🐅', type: 'image', doc: require('../assets/img/png/1f405.png'), correctWord: 'Tigre', difficulty: 2},
    {string: '🐆', type: 'image', doc: require('../assets/img/png/1f406.png'), correctWord: 'Léopard', difficulty: 3},
    {string: '🐇', type: 'image', doc: require('../assets/img/png/1f407.png'), correctWord: 'Lapin', difficulty: 2},
    {string: '🐈', type: 'image', doc: require('../assets/img/png/1f408.png'), correctWord: 'Chat', difficulty: 2},
    {string: '🐉', type: 'image', doc: require('../assets/img/png/1f409.png'), correctWord: 'Dragon', difficulty: 2},
    {string: '🐊', type: 'image', doc: require('../assets/img/png/1f40a.png'), correctWord: 'Crocodile', difficulty: 1},
    {string: '🐋', type: 'image', doc: require('../assets/img/png/1f40b.png'), correctWord: 'Baleine', difficulty: 2},
    {string: '🐌', type: 'image', doc: require('../assets/img/png/1f40c.png'), correctWord: 'Escargot', difficulty: 2},
    {string: '🐍', type: 'image', doc: require('../assets/img/png/1f40d.png'), correctWord: 'Serpent', difficulty: 2},
    {string: '🐎', type: 'image', doc: require('../assets/img/png/1f40e.png'), correctWord: 'Cheval', difficulty: 2},
    {string: '🐏', type: 'image', doc: require('../assets/img/png/1f40f.png'), correctWord: 'Mouton', words:{level_3: ['Montagne', 'Mousse', 'Moulin', 'Marteau', 'Maison']}, difficulty: 2},
    {string: '🐐', type: 'image', doc: require('../assets/img/png/1f410.png'), correctWord: 'Chèvre', difficulty: 2},
    {string: '🐒', type: 'image', doc: require('../assets/img/png/1f412.png'), correctWord: 'Singe', words:{level_3: ['Serpent', 'Soleil', 'Cerise', 'Chien', 'Chat']}, difficulty: 2},
    {string: '🐓', type: 'image', doc: require('../assets/img/png/1f413.png'), correctWord: 'Coq', difficulty: 2},
    {string: '🐕', type: 'image', doc: require('../assets/img/png/1f415.png'), correctWord: 'Chien', difficulty: 2},
    {string: '🐖', type: 'image', doc: require('../assets/img/png/1f416.png'), correctWord: 'Cochon', difficulty: 2},
    {string: '🐘', type: 'image', doc: require('../assets/img/png/1f418.png'), correctWord: 'Éléphant', difficulty: 3},
    {string: '🐙', type: 'image', doc: require('../assets/img/png/1f419.png'), correctWord: 'Poulpe', difficulty: 3},
    {string: '🐚', type: 'image', doc: require('../assets/img/png/1f41a.png'), correctWord: 'Coquillage', difficulty: 4},
    {string: '🐛', type: 'image', doc: require('../assets/img/png/1f41b.png'), correctWord: 'Chenille', difficulty: 3},
    {string: '🐜', type: 'image', doc: require('../assets/img/png/1f41c.png'), correctWord: 'Fourmi', difficulty: 2},
    {string: '🐝', type: 'image', doc: require('../assets/img/png/1f41d.png'), correctWord: 'Abeille', words:{level_3: ['Appareil photo', 'Ampoule', 'Avocat', 'Ancre', 'Avion']}, difficulty: 2},
    {string: '🐞', type: 'image', doc: require('../assets/img/png/1f41e.png'), correctWord: 'Coccinelle', difficulty: 3},
    {string: '🐟', type: 'image', doc: require('../assets/img/png/1f41f.png'), correctWord: 'Poisson', difficulty: 2},
    {string: '🐠', type: 'image', doc: require('../assets/img/png/1f420.png'), correctWord: 'Poisson', difficulty: 2},
    {string: '🐢', type: 'image', doc: require('../assets/img/png/1f422.png'), correctWord: 'Tortue', difficulty: 2},
    {string: '🐣', type: 'image', doc: require('../assets/img/png/1f423.png'), correctWord: 'Poussin', difficulty: 2},
    {string: '🐩', type: 'image', doc: require('../assets/img/png/1f429.png'), correctWord: 'Chien', difficulty: 2},
    {string: '🐫', type: 'image', doc: require('../assets/img/png/1f42b.png'), correctWord: 'Chameau', difficulty: 3},
    {string: '🐬', type: 'image', doc: require('../assets/img/png/1f42c.png'), correctWord: 'Dauphin', words:{level_3: ['Dromadaire', 'Dragon', 'Dé', 'Danser', 'Grue']}, difficulty: 3},
    {string: '🐿', type: 'image', doc: require('../assets/img/png/1f43f.png'), correctWord: 'Écureuil', words:{level_3: ['Éléphant', 'Étoile', 'Café', 'Poussin', 'Maïs']}, difficulty: 3},
    {string: '👃', type: 'image', doc: require('../assets/img/png/1f443.png'), correctWord: 'Nez', difficulty: 3},
    {string: '👄', type: 'image', doc: require('../assets/img/png/1f444.png'), correctWord: 'Bouche', difficulty: 2},
    {string: '👓', type: 'image', doc: require('../assets/img/png/1f453.png'), correctWord: 'Lunettes', difficulty: 2},
    {string: '👕', type: 'image', doc: require('../assets/img/png/1f455.png'), correctWord: 'Chemise', difficulty: 2},
    {string: '👖', type: 'image', doc: require('../assets/img/png/1f456.png'), correctWord: 'Pantalon', difficulty: 2},
    {string: '👗', type: 'image', doc: require('../assets/img/png/1f457.png'), correctWord: 'Robe', difficulty: 1},
    {string: '👞', type: 'image', doc: require('../assets/img/png/1f45e.png'), correctWord: 'Chaussure', difficulty: 3},
    {string: '👟', type: 'image', doc: require('../assets/img/png/1f45f.png'), correctWord: 'Chaussure', difficulty: 3},
    {string: '👠', type: 'image', doc: require('../assets/img/png/1f460.png'), correctWord: 'Chaussure', difficulty: 3},
    {string: '👡', type: 'image', doc: require('../assets/img/png/1f461.png'), correctWord: 'Chaussure', difficulty: 3},
    {string: '💡', type: 'image', doc: require('../assets/img/png/1f4a1.png'), correctWord: 'Ampoule', difficulty: 2},
    {string: '💼', type: 'image', doc: require('../assets/img/png/1f4bc.png'), correctWord: 'Valise', difficulty: 1},
    {string: '📸', type: 'image', doc: require('../assets/img/png/1f4f8.png'), correctWord: 'Appareil Photo', difficulty: 4},
    {string: '🔔', type: 'image', doc: require('../assets/img/png/1f514.png'), correctWord: 'Cloche', difficulty: 2},
    {string: '🔥', type: 'image', doc: require('../assets/img/png/1f525.png'), correctWord: 'Feu', difficulty: 2},
    {string: '🔦', type: 'image', doc: require('../assets/img/png/1f526.png'), correctWord: 'Lampe', difficulty: 2},
    {string: '🔨', type: 'image', doc: require('../assets/img/png/1f528.png'), correctWord: 'Marteau', difficulty: 2},
    {string: '🕺', type: 'image', doc: require('../assets/img/png/1f57a.png'), correctWord: 'Danser', difficulty: 2},
    {string: '🖨', type: 'image', doc: require('../assets/img/png/1f5a8.png'), correctWord: 'Imprimante', difficulty: 3},
    {string: '🙁', type: 'image', doc: require('../assets/img/png/1f641.png'), correctWord: 'Triste', difficulty: 2},
    {string: '🙇', type: 'image', doc: require('../assets/img/png/1f647.png'), correctWord: 'Dommage'},
    {string: '🚛', type: 'image', doc: require('../assets/img/png/1f69b.png'), correctWord: 'Camion', difficulty: 2},
    {string: '🚜', type: 'image', doc: require('../assets/img/png/1f69c.png'), correctWord: 'Tracteur', difficulty: 2},
    {string: '🚣', type: 'image', doc: require('../assets/img/png/1f6a3.png'), correctWord: 'Ramer', difficulty: 3},
    {string: '🚲', type: 'image', doc: require('../assets/img/png/1f6b2.png'), correctWord: 'Vélo', difficulty: 1},
    {string: '🚴', type: 'image', doc: require('../assets/img/png/1f6b4.png'), correctWord: 'Vélo', difficulty: 1},
    {string: '🚶', type: 'image', doc: require('../assets/img/png/1f6b6.png'), correctWord: 'Marcher', difficulty: 3},
    {string: '🚽', type: 'image', doc: require('../assets/img/png/1f6bd.png'), correctWord: 'Toilette', difficulty: 3},
    {string: '🛀', type: 'image', doc: require('../assets/img/png/1f6c0.png'), correctWord: 'Baignoire', difficulty: 3},
    {string: '🛣', type: 'image', doc: require('../assets/img/png/1f6e3.png'), correctWord: 'Route', difficulty: 2},
    {string: '🛰', type: 'image', doc: require('../assets/img/png/1f6f0.png'), correctWord: 'Satellite', difficulty: 3},
    {string: '🤦', type: 'image', doc: require('../assets/img/png/1f926.png'), correctWord: 'Oups'},
    {string: '🤷', type: 'image', doc: require('../assets/img/png/1f937.png'), correctWord: 'Dommage'},
    {string: '🤹', type: 'image', doc: require('../assets/img/png/1f939.png'), correctWord: 'Jongler', words: {level_4: ['Avocat', 'Satellite', 'Concombre', 'Pain', 'Carotte']}, difficulty: 4},
    {string: '🥁', type: 'image', doc: require('../assets/img/png/1f941.png'), correctWord: 'Tambour', words: {level_4: ['Tourner', 'Satellite', 'Baignoire', 'Marcher', 'Jongler']}, difficulty: 3},
    {string: '🥐', type: 'image', doc: require('../assets/img/png/1f950.png'), correctWord: 'Croissant', words: {level_4: ['Cygne', 'Satellite', 'Baignoire', 'Marcher', 'Jongler']}, difficulty: 3},
    {string: '🥑', type: 'image', doc: require('../assets/img/png/1f951.png'), correctWord: 'Avocat', words: {level_4: ['Avion', 'Carotte', 'Kiwi', 'Croissant', 'Jongler']}, difficulty: 2},
    {string: '🥒', type: 'image', doc: require('../assets/img/png/1f952.png'), correctWord: 'Concombre', words: {level_4: ['Cygne', 'Carotte', 'Kiwi', 'Croissant', 'Jongler']}, difficulty: 3},
    {string: '🥕', type: 'image', doc: require('../assets/img/png/1f955.png'), correctWord: 'Carotte', difficulty: 2},
    {string: '🥖', type: 'image', doc: require('../assets/img/png/1f956.png'), correctWord: 'Pain', difficulty: 3},
    {string: '🥝', type: 'image', doc: require('../assets/img/png/1f95d.png'), correctWord: 'Kiwi', words: {level_4: ['Cygne', 'Carotte', 'Singe', 'Croissant', 'Tambour']}, difficulty: 1},
    {string: '🦄', type: 'image', doc: require('../assets/img/png/1f984.png'), correctWord: 'Licorne', words:{level_4: ['Limace', 'Ligne', 'Lecture', 'Carotte', 'Kiwi']}, difficulty: 2},
    {string: '🦅', type: 'image', doc: require('../assets/img/png/1f985.png'), correctWord: 'Aigle', difficulty: 2},
    {string: '🦆', type: 'image', doc: require('../assets/img/png/1f986.png'), correctWord: 'Canard', words:{level_4: ['Canapé', 'Chemise', 'Fauteuil', 'Carotte', 'concombre']}, difficulty: 1},
    {string: '🦇', type: 'image', doc: require('../assets/img/png/1f987.png'), correctWord: 'Chauve-souris', words:{level_4: ['Requin', 'Eléphant', 'Canard', 'Licorne', 'Pain']}, difficulty: 4},
    {string: '🦈', type: 'image', doc: require('../assets/img/png/1f988.png'), correctWord: 'Requin', words:{level_4: ['Râpe', 'Roue', 'Rire', 'Cerf-volant', 'Maison']}, difficulty: 3},
    {string: '🦉', type: 'image', doc: require('../assets/img/png/1f989.png'), correctWord: 'Hibou', words:{level_4: ['Hôtel', 'Aigle', 'Avion', 'Cerf-volant', 'Maison']}, difficulty: 2},
    {string: '☕', type: 'image', doc: require('../assets/img/png/2615.png'), correctWord: 'Café', difficulty: 1},
    {string: '⚓', type: 'image', doc: require('../assets/img/png/2693.png'), correctWord: 'Ancre', words:{level_3: ['Avion', 'Ampoule', 'Ananas', 'Aubergine', 'Aigle']}, difficulty: 2},
    {string: '✂', type: 'image', doc: require('../assets/img/png/2702.png'), correctWord: 'Ciseaux', words:{level_4: ['Canapé', 'Scie', 'Siège', 'Silex', 'Feu']}, difficulty: 3},
    {string: '✈', type: 'image', doc: require('../assets/img/png/2708.png'), correctWord: 'Avion', words:{level_3: ['Ancre', 'Ampoule', 'Ananas', 'Aubergine', 'Aigle']}, difficulty: 2},
]

export default allMedia